#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and

hour=0
min=1

while [ $hour -le 12 ];
do
	echo "Hour: $hour"

while [ $min -le 59 ];
do
	echo $min
	((min++))
done
	min=1
	((hour++))
done
